#!/bin/bash
source "$HOME/dotfiles/bash/color_scheme"
source "$HOME/dotfiles/bash/ls_colors"

alias l='ls -hXF --color=auto'
alias ls='ls -lhXF --color=auto'
alias lsa='ls -lahXF --color=auto'
alias gpgla='gpg2 --list-keys --keyid-format LONG --fingerprint'
alias gpgsla='gpg2 --list-secret-keys --keyid-format LONG --fingerprint'
alias ports='lsof -i -n -P'
alias services_enabled='systemctl list-unit-files | ag enable'
alias services_disabled='systemctl list-unit-files | ag disable'
alias ssh='ssh -XYC'
alias rsync='rsync --progress'
alias rrsync='rsync -r --progress'
alias agh='ag --hidden'
alias ssh-secure-keygen='ssh-keygen -o -a 100 -t ed25519'
alias sysup='sudo apt update && sudo apt full-upgrade -y && sudo apt autoremove -y'

# Kenny custom configs
export EDITOR=vim
export TERMINAL=urxvt
export BROWSER=vivaldi

# Enable 256 colors for terminal
export TERM=screen-256color

# Enable case insensitive tab completion
bind 'set completion-ignore-case on'

# Auto-fix type
shopt -s cdspell

# Disable virtualenv from changing PS1
export VIRTUAL_ENV_DISABLE_PROMPT=1

# Disable .pyc generation
export PYTHONDONTWRITEBYTECODE=1

# Cycle through autocomplete candidates
#bind 'set show-all-if-ambiguous on'
bind Control-j:menu-complete
bind Control-k:menu-complete-backward

###########################
# Helper functions        #
###########################
# Poll status
function get_status {
    echo -e ""
    echo -e "         _____           "
    echo -e "       ./_|L|__\.        ${BGre}Welcome back Apo11oH${RCol}"
    echo -e "      / ==[_]O|| \       ${BRed}Shall we play a game?${RCol}"
    echo -e "     _:=||____|.|-:_     "
    echo -e "    ||[] ||====| []||    ${BBlu}Arch:\t\t${RCol}$(uname -m) "
    echo -e "    |:||_|=|U| |_||:|    ${BBlu}Hostname:\t${RCol}$(hostname)"
    echo -e "    |:||[]_=_ =[_||:|    ${BBlu}Uptime:\t${RCol}$(uptime -p)"
    echo -e "    | ||[] [_][]C|| |    ${BBlu}Kernel:\t${RCol}$(uname -r)"
    echo -e "    /|\\_\_|_|_/_//||\    ${BBlu}Shell:\t\t${RCol}$(ps -p$$ -ocmd='')"
    echo -e "   |___|   /|\   |___|   "
    echo -e "   \---/  |___|  \---/   "
    echo -e ""
}
alias status=get_status

function setup_ssh_agent {
    if ! pgrep -u "$USER" ssh-agent > /dev/null; then
        ssh-agent > ~/.ssh-agent-pid
    fi
    if [[ "$SSH_AGENT_PID" == "" ]]; then
        eval "$(<~/.ssh-agent-pid)"
    fi
}

function setup_gpg_agent {
    if ! pgrep -u "$USER" gpg-agent > /dev/null; then
        gpg-agent --daemon --sh
    fi
}

######################
# Custom Bash Prompt #
######################
# Parse git branch
function parse_git_branch {
    git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/(\1)/'
}

function meta {
    echo "$(ls -1 | sed 1d | wc -l | sed 's: ::g') files, $(ls -sh | head -n1 | sed 's/total //')b"
}

virtual_env_detector() {
  if [[ -n "$VIRTUAL_ENV" ]]; then
    echo "($(basename "${VIRTUAL_ENV:-""}")) "
  else
    echo ""
  fi
}

SSH_COLOR='\[\033[1;35m\]'; VENV_COLOR='\[\033[1;36m\]';
DCOL='\[\033[1;37m\]'; STATCOL='\[\033[1;34m\]'; CWDCOL='\[\033[1;32m\]'
METACOL='\[\033[1;32m\]'; RST='\[\033[0m\]'
[[ ${EUID} == 0 ]] && USER_COL='\[\033[01;31m\]' || USER_COL='\[\033[01;34m\]'
[[ "$SSH_CONNECTION" ]] && HOST_ADDR="$(echo "$SSH_CONNECTION" | awk '{print $3}')"
[[ "$SSH_CONNECTION" ]] && USER_HOST="${SSH_COLOR}\u@$HOST_ADDR${DCOL}" || USER_HOST="\u@\h"
PS1="${VENV_COLOR}\$(virtual_env_detector)${DCOL}>> ${USER_COL}${USER_HOST}${DCOL} >> ${STATCOL}\$?${DCOL} >> "
PS1+="${STATCOL}\@ \d${DCOL}${DCOL} \$(parse_git_branch)\n>> ${CWDCOL}\w${DCOL} >> \$${RST} "
#PS1+="${METACOL}\$(meta)${DCOL} \$${RST} "

# Start programs
setup_ssh_agent &> /dev/null
setup_gpg_agent &> /dev/null
